/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pc.view;

import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pc.controler.HangControl;
import pc.controler.NCCControl;
import pc.controler.NhanVienControl;
import pc.controler.PhieuNhapControl;
import pc.controler.PhieuXuatControl;
import pc.controler.TangControl;
import pc.model.HangModel;
import pc.model.NCCModel;
import pc.model.NhanVienModel;
import pc.model.PhieuNhapModel;
import pc.model.PhieuXuatModel;
import pc.model.TangModel;

/**
 *
 * @author Administrator
 */
public class frm_XuatNhapHang extends javax.swing.JFrame {

    /**
     * Creates new form frm_XuatNhapHang
     */
    private double tongTienNhap = 0;
    private double tongTienXuat = 0;

    public frm_XuatNhapHang() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Xử lý khi form được đóng
                frm_MeNu formMeNu = new frm_MeNu();
                formMeNu.setVisible(true);
                formMeNu.setLocationRelativeTo(null);
            }
        });
        loadComBoBoxMaHang1();
        loadComBoBoxMaHang2();

        loadComBoBoxMaNhanVien1();
        loadComBoBoxMaNhanVien2();

        loadComBoBoxMaNCC();

        LoadDuLieu3();
        loadComBoBoxMaTang();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaPhieuNhap = new javax.swing.JTextField();
        txtMaNhanVien1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaNCC = new javax.swing.JTextField();
        txtNgayNhap1 = new javax.swing.JTextField();
        txtSoLuong1 = new javax.swing.JTextField();
        btnThem1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtTong1 = new javax.swing.JTextField();
        btnLuuPhieu1 = new javax.swing.JButton();
        jcbMaHang1 = new javax.swing.JComboBox<>();
        jcbMaNhanVienNhap = new javax.swing.JComboBox<>();
        jcbMaNCC = new javax.swing.JComboBox<>();
        btnLamMoi1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaPhieuXuat = new javax.swing.JTextField();
        txtMaNhanVien2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNgayNhap2 = new javax.swing.JTextField();
        txtSoLuong2 = new javax.swing.JTextField();
        btnThem2 = new javax.swing.JButton();
        btnXoa2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtTong2 = new javax.swing.JTextField();
        btnLuuPhieu2 = new javax.swing.JButton();
        jcbMaHang2 = new javax.swing.JComboBox<>();
        jcbMaNhanVienXuat = new javax.swing.JComboBox<>();
        btnLamMoi2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtMaHang3 = new javax.swing.JTextField();
        txtTenHang3 = new javax.swing.JTextField();
        txtDonGia3 = new javax.swing.JTextField();
        btnTimKiem3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtDonViTinh3 = new javax.swing.JTextField();
        txtSoLuong3 = new javax.swing.JTextField();
        btnThem3 = new javax.swing.JButton();
        btnSua3 = new javax.swing.JButton();
        btnXoa3 = new javax.swing.JButton();
        cbx3 = new javax.swing.JComboBox<>();
        btnLamMoi3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtMaTang3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHang3 = new javax.swing.JTable();
        jcbMaTang = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lí xuất nhập hàng");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mã phiếu nhập");

        jLabel2.setText("Mã Nhân Viên");

        jLabel3.setText("Mã hàng");

        txtMaNhanVien1.setEditable(false);

        jLabel4.setText("Mã NCC");

        jLabel5.setText("Ngày nhập");

        jLabel6.setText("Số lượng");

        txtMaNCC.setEditable(false);

        btnThem1.setText("Thêm");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnXoa1.setText("Xóa");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hàng", "Tên hàng", "Đơn giá", "Đơn vị tính", "Số lượng"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setText("Tổng");

        txtTong1.setEditable(false);

        btnLuuPhieu1.setText("Lưu phiếu");
        btnLuuPhieu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuPhieu1ActionPerformed(evt);
            }
        });

        jcbMaNhanVienNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMaNhanVienNhapActionPerformed(evt);
            }
        });

        jcbMaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMaNCCActionPerformed(evt);
            }
        });

        btnLamMoi1.setText("Làm mới");
        btnLamMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoi1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7)
                        .addGap(32, 32, 32)
                        .addComponent(txtTong1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLamMoi1)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuuPhieu1)
                        .addGap(19, 19, 19))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(txtMaPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMaNhanVien1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                        .addComponent(jcbMaHang1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbMaNhanVienNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgayNhap1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaNCC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThem1)
                                    .addComponent(btnXoa1))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtNgayNhap1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbMaNhanVienNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbMaHang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem1))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSoLuong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa1))
                .addGap(84, 84, 84)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuPhieu1)
                    .addComponent(btnLamMoi1))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Nhập hàng", jPanel1);

        jLabel8.setText("Mã phiếu xuất");

        jLabel9.setText("Mã nhân viên");

        jLabel10.setText("Mã hàng");

        txtMaNhanVien2.setEditable(false);

        jLabel11.setText("Ngày nhập");

        jLabel12.setText("Số lượng");

        btnThem2.setText("Thêm");
        btnThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem2ActionPerformed(evt);
            }
        });

        btnXoa2.setText("Xóa");
        btnXoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hàng", "Tên hàng", "Đơn giá", "Đơn vị tính", "Số lượng"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel13.setText("Tổng");

        txtTong2.setEditable(false);

        btnLuuPhieu2.setText("Lưu phiếu");
        btnLuuPhieu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuPhieu2ActionPerformed(evt);
            }
        });

        jcbMaNhanVienXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMaNhanVienXuatActionPerformed(evt);
            }
        });

        btnLamMoi2.setText("Làm mới");
        btnLamMoi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoi2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSoLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMaNhanVien2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(jcbMaHang2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbMaNhanVienXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNgayNhap2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnXoa2)
                                    .addComponent(btnThem2))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(59, 59, 59)
                        .addComponent(txtMaPhieuXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)))
                .addGap(85, 85, 85))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel13)
                .addGap(30, 30, 30)
                .addComponent(txtTong2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLamMoi2)
                .addGap(18, 18, 18)
                .addComponent(btnLuuPhieu2)
                .addGap(91, 91, 91))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMaNhanVien2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbMaNhanVienXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(56, 56, 56))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMaPhieuXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtNgayNhap2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jcbMaHang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThem2))))
                        .addGap(57, 57, 57))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtSoLuong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXoa2)))
                .addGap(64, 64, 64)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuPhieu2)
                    .addComponent(btnLamMoi2))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Xuất hàng", jPanel4);

        jLabel14.setText("Mã hàng");

        jLabel15.setText("Tên hàng");

        jLabel16.setText("Đơn giá");

        btnTimKiem3.setText("Tìm kiếm");
        btnTimKiem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiem3ActionPerformed(evt);
            }
        });

        jLabel17.setText("Đơn vị tính");

        jLabel18.setText("Số lượng");

        btnThem3.setText("Thêm");
        btnThem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem3ActionPerformed(evt);
            }
        });

        btnSua3.setText("Sửa");
        btnSua3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua3ActionPerformed(evt);
            }
        });

        btnXoa3.setText("Xóa");
        btnXoa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa3ActionPerformed(evt);
            }
        });

        cbx3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx3ActionPerformed(evt);
            }
        });

        btnLamMoi3.setText("Làm mới");
        btnLamMoi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoi3ActionPerformed(evt);
            }
        });

        jLabel19.setText("Tầng");

        txtMaTang3.setEditable(false);

        tblHang3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHang3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHang3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblHang3);

        jcbMaTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMaTangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(cbx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenHang3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaHang3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDonGia3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTimKiem3)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaTang3, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(txtDonViTinh3)
                                    .addComponent(txtSoLuong3))
                                .addGap(18, 18, 18)
                                .addComponent(jcbMaTang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnLamMoi3)
                                .addGap(44, 44, 44)
                                .addComponent(btnThem3)
                                .addGap(48, 48, 48)
                                .addComponent(btnSua3)
                                .addGap(49, 49, 49)
                                .addComponent(btnXoa3)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtMaHang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem3)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaTang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbMaTang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTenHang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtDonViTinh3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtDonGia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtSoLuong3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLamMoi3)
                    .addComponent(btnThem3)
                    .addComponent(btnSua3)
                    .addComponent(btnXoa3))
                .addGap(62, 62, 62)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Thông tin hàng hóa", jPanel5);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 748, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // TODO add your handling code here:

        loadThongTinNhapHang();
        // updateSoLuongHangSauKhiNhapHang();
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem2ActionPerformed
        // TODO add your handling code here:

        loadThongTinXuatHang();
    }//GEN-LAST:event_btnThem2ActionPerformed

    private void btnLuuPhieu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuPhieu2ActionPerformed
        // TODO add your handling code here:
        luuPhieuXuat();
    }//GEN-LAST:event_btnLuuPhieu2ActionPerformed

    private void btnLuuPhieu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuPhieu1ActionPerformed
        // TODO add your handling code here:
        luuPhieuNhap();

    }//GEN-LAST:event_btnLuuPhieu1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        // TODO add your handling code here:
        xoaThongTinNhapHang();

    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
//        // TODO add your handling code here:
//        if (this.jTable1.getSelectedRow() >= 0) {
//            String soLuong = this.jTable1.getValueAt(this.jTable1.getSelectedRow(), 4).toString();
//            txtSoLuong1.setText(soLuong);
//
//            int row = jTable1.getSelectedRow();
//            String maHang = jTable1.getValueAt(row, 0).toString();
//            txtMaNCC.setText(maHang);
//            //System.out.println(maHang);
//            jcbMaHang1.setSelectedItem(maHang);
//
//        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnXoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa2ActionPerformed
        // TODO add your handling code here:
        xoaThongTinXuatHang();
    }//GEN-LAST:event_btnXoa2ActionPerformed

    private void jcbMaNhanVienNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMaNhanVienNhapActionPerformed
        // TODO add your handling code here:
        txtMaNhanVien1.setText(jcbMaNhanVienNhap.getSelectedItem().toString());
    }//GEN-LAST:event_jcbMaNhanVienNhapActionPerformed

    private void jcbMaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMaNCCActionPerformed
        // TODO add your handling code here:
        txtMaNCC.setText(jcbMaNCC.getSelectedItem().toString());
    }//GEN-LAST:event_jcbMaNCCActionPerformed

    private void jcbMaNhanVienXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMaNhanVienXuatActionPerformed
        // TODO add your handling code here:
        txtMaNhanVien2.setText(jcbMaNhanVienXuat.getSelectedItem().toString());
    }//GEN-LAST:event_jcbMaNhanVienXuatActionPerformed

    private void btnLamMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoi1ActionPerformed
        // TODO add your handling code here:
        txtMaPhieuNhap.setText("");
        txtNgayNhap1.setText("");
        loadComBoBoxMaHang1();
        loadComBoBoxMaNCC();
        loadComBoBoxMaNhanVien1();
        txtMaNhanVien1.setText("");
        txtMaNCC.setText("");
        txtSoLuong1.setText("");
        txtTong1.setText("");
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);


    }//GEN-LAST:event_btnLamMoi1ActionPerformed

    private void btnLamMoi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoi2ActionPerformed
        // TODO add your handling code here:
        txtMaPhieuXuat.setText("");
        txtNgayNhap2.setText("");
        loadComBoBoxMaHang2();

        loadComBoBoxMaNhanVien2();
        txtMaNhanVien2.setText("");

        txtSoLuong2.setText("");
        txtTong2.setText("");
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

        model.setRowCount(0);
    }//GEN-LAST:event_btnLamMoi2ActionPerformed

    private void btnTimKiem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiem3ActionPerformed
        TimKiem3();
    }//GEN-LAST:event_btnTimKiem3ActionPerformed

    private void btnThem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem3ActionPerformed
        Them3();
    }//GEN-LAST:event_btnThem3ActionPerformed

    private void btnSua3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua3ActionPerformed
        Sua3();
    }//GEN-LAST:event_btnSua3ActionPerformed

    private void btnXoa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa3ActionPerformed
        Xoa3();
    }//GEN-LAST:event_btnXoa3ActionPerformed

    private void cbx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx3ActionPerformed
        String kt = cbx3.getSelectedItem().toString();
        LoadTable3(kt);
    }//GEN-LAST:event_cbx3ActionPerformed

    private void btnLamMoi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoi3ActionPerformed
        LamMoi3();
    }//GEN-LAST:event_btnLamMoi3ActionPerformed

    private void tblHang3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHang3MouseClicked

//        HangControl hgcontrol = new HangControl();
//        ArrayList<HangModel> ds = hgcontrol.docThongTinHang();
//        int row = tblHang3.getSelectedRow();
//        if (row == -1) {
//            return;
//        }
//        HangModel hgmodel = ds.get(row);
//        txtMaHang3.setText(hgmodel.getMaHang());
//        txtTenHang3.setText(hgmodel.getTenHang());
//        txtDonViTinh3.setText(hgmodel.getDonViTinh());
//        txtSoLuong3.setText(hgmodel.getSoLuong() + "");
//        txtDonGia3.setText(hgmodel.getDonGia() + "");
//        txtMaTang3.setText(hgmodel.getMaTang());
        tbleHangMouseClickedTUAN(evt);
    }//GEN-LAST:event_tblHang3MouseClicked

    private void jcbMaTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMaTangActionPerformed
        // TODO add your handling code here:
        txtMaTang3.setText(jcbMaTang.getSelectedItem().toString());
    }//GEN-LAST:event_jcbMaTangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_XuatNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_XuatNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_XuatNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_XuatNhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_XuatNhapHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi1;
    private javax.swing.JButton btnLamMoi2;
    private javax.swing.JButton btnLamMoi3;
    private javax.swing.JButton btnLuuPhieu1;
    private javax.swing.JButton btnLuuPhieu2;
    private javax.swing.JButton btnSua3;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnThem3;
    private javax.swing.JButton btnTimKiem3;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JButton btnXoa2;
    private javax.swing.JButton btnXoa3;
    private javax.swing.JComboBox<String> cbx3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox<String> jcbMaHang1;
    private javax.swing.JComboBox<String> jcbMaHang2;
    private javax.swing.JComboBox<String> jcbMaNCC;
    private javax.swing.JComboBox<String> jcbMaNhanVienNhap;
    private javax.swing.JComboBox<String> jcbMaNhanVienXuat;
    private javax.swing.JComboBox<String> jcbMaTang;
    private javax.swing.JTable tblHang3;
    private javax.swing.JTextField txtDonGia3;
    private javax.swing.JTextField txtDonViTinh3;
    private javax.swing.JTextField txtMaHang3;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtMaNhanVien1;
    private javax.swing.JTextField txtMaNhanVien2;
    private javax.swing.JTextField txtMaPhieuNhap;
    private javax.swing.JTextField txtMaPhieuXuat;
    private javax.swing.JTextField txtMaTang3;
    private javax.swing.JTextField txtNgayNhap1;
    private javax.swing.JTextField txtNgayNhap2;
    private javax.swing.JTextField txtSoLuong1;
    private javax.swing.JTextField txtSoLuong2;
    private javax.swing.JTextField txtSoLuong3;
    private javax.swing.JTextField txtTenHang3;
    private javax.swing.JTextField txtTong1;
    private javax.swing.JTextField txtTong2;
    // End of variables declaration//GEN-END:variables

    public void loadThongTinNhapHang() {
        String maHang = jcbMaHang1.getSelectedItem().toString().substring(0,4);
        String soLuong = txtSoLuong1.getText();
        int sl;
        double donGia;
        if (soLuong.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số lượng");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        HangControl hangControl = new HangControl();
        ArrayList<HangModel> ds = hangControl.layThongTinHang(maHang);

        for (HangModel d : ds) {
            donGia = d.getDonGia();
            sl = Integer.parseInt(soLuong);
            double tongTienHang = donGia * sl;
            tongTienNhap = tongTienNhap + tongTienHang;
            Object[] row = {
                d.getMaHang(),
                d.getTenHang(),
                d.getDonGia(),
                d.getDonViTinh(),
                soLuong
            };
            model.addRow(row);
//            int soLuongMoi = d.getSoLuong() + Integer.parseInt(soLuong);
//            int k = hangControl.suaSoLuongHangSauKhiNhapHang(maHang, soLuongMoi);
//            System.out.println(soLuongMoi);
//            System.out.println(k);
        }
        txtTong1.setText(String.valueOf(tongTienNhap));

    }

    public void xoaThongTinNhapHang() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int soHang = model.getRowCount();

        if (soHang == 0) {
            JOptionPane.showMessageDialog(null, "Bảng không có dữ liệu để xóa.");
            return;
        }

        String maHangXoa = jcbMaHang1.getSelectedItem().toString();

//        int kiemTraATonTaiMa = -1;
//        for (int i = 0; i < soHang; i++) {
//            if (model.getValueAt(i, 0).equals(maHangXoa)) {
//                kiemTraATonTaiMa = i;
//                break;
//            }
//        }
//        if (kiemTraATonTaiMa != -1) {
//            model.removeRow(kiemTraATonTaiMa);
//        } else {
//            JOptionPane.showMessageDialog(null, "Không tồn tại mã hàng này trong Bảng");
//            return;
//        }
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) { // Kiểm tra hàng được chọn có hợp lệ không
            // Xóa hàng khỏi mô hình dữ liệu của JTable
            model.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng để xóa.");
        }

        double tongTien = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            double donGia = (double) model.getValueAt(i, 2);
            int soLuong = Integer.parseInt((String) model.getValueAt(i, 4));
            tongTien += donGia * soLuong;
        }
        tongTienNhap = tongTien;
        txtTong1.setText(String.valueOf(tongTienNhap));
    }

    public void loadThongTinXuatHang() {
        String maHang = jcbMaHang2.getSelectedItem().toString().substring(0,4);
        String soLuong = txtSoLuong2.getText();
        int sl;
        double donGia;
        if (soLuong.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số lượng");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

        HangControl hangControl = new HangControl();
        ArrayList<HangModel> ds = hangControl.layThongTinHang(maHang);

        for (HangModel d : ds) {
            donGia = d.getDonGia();
            sl = Integer.parseInt(soLuong);
            double tongTienHang = donGia * sl;
            tongTienXuat = tongTienXuat + tongTienHang;
            Object[] row = {
                d.getMaHang(),
                d.getTenHang(),
                d.getDonGia(),
                d.getDonViTinh(),
                soLuong
            };
            model.addRow(row);
        }
        txtTong2.setText(String.valueOf(tongTienXuat));
    }

    public void xoaThongTinXuatHang() {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int soHang = model.getRowCount();

        if (soHang == 0) {
            JOptionPane.showMessageDialog(null, "Bảng không có dữ liệu để xóa.");
            return;
        }

        String maHangXoa = jcbMaHang2.getSelectedItem().toString();

        int kiemTraATonTaiMa = -1;
        for (int i = 0; i < soHang; i++) {
            if (model.getValueAt(i, 0).equals(maHangXoa)) {
                kiemTraATonTaiMa = i;
                break;
            }
        }
        if (kiemTraATonTaiMa != -1) {
            model.removeRow(kiemTraATonTaiMa);
        } else {
            JOptionPane.showMessageDialog(null, "Không tồn tại mã hàng này trong Bảng");
            return;
        }
        double tongTien = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            double donGia = (double) model.getValueAt(i, 2);
            int soLuong = Integer.parseInt((String) model.getValueAt(i, 4));
            tongTien += donGia * soLuong;
        }
        tongTienXuat = tongTien;
        txtTong2.setText(String.valueOf(tongTienXuat));
    }

    public void loadComBoBoxMaHang1() {
        HangControl hangControl = new HangControl();
        ArrayList<HangModel> ds = hangControl.layThongTinComBoBoxHang();
        DefaultComboBoxModel cbo = new DefaultComboBoxModel();
        for (HangModel d : ds) {
            cbo.addElement(d);
        }
        jcbMaHang1.setModel(cbo);
        //jcbMaHang2.setModel(cbo);
    }

    public void loadComBoBoxMaHang2() {
        HangControl hangControl = new HangControl();
        ArrayList<HangModel> ds = hangControl.layThongTinComBoBoxHang();
        DefaultComboBoxModel cbo = new DefaultComboBoxModel();
        for (HangModel d : ds) {
            cbo.addElement(d);
        }
        //jcbMaHang1.setModel(cbo);
        jcbMaHang2.setModel(cbo);
    }

    public void loadComBoBoxMaNhanVien1() {
        NhanVienControl nvconControl = new NhanVienControl();
        ArrayList<NhanVienModel> ds = nvconControl.layThongTinComBoBoxNhanVien();
        DefaultComboBoxModel cbo = new DefaultComboBoxModel();
        for (NhanVienModel d : ds) {
            cbo.addElement(d);
        }
        jcbMaNhanVienNhap.setModel(cbo);
        //jcbMaNhanVienXuat.setModel(cbo);
    }

    public void loadComBoBoxMaNhanVien2() {
        NhanVienControl nvconControl = new NhanVienControl();
        ArrayList<NhanVienModel> ds = nvconControl.layThongTinComBoBoxNhanVien();
        DefaultComboBoxModel cbo = new DefaultComboBoxModel();
        for (NhanVienModel d : ds) {
            cbo.addElement(d);
        }
        //jcbMaNhanVienNhap.setModel(cbo);
        jcbMaNhanVienXuat.setModel(cbo);
    }

    public void loadComBoBoxMaNCC() {
        NCCControl nCCControl = new NCCControl();
        ArrayList<NCCModel> ds = nCCControl.layThongTinComBoBoxNCC();
        DefaultComboBoxModel cbo = new DefaultComboBoxModel();

        for (NCCModel d : ds) {
            cbo.addElement(d);
        }
        jcbMaNCC.setModel(cbo);
    }

    public void luuPhieuNhap() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            if (txtMaPhieuNhap.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập Mã phiếu nhập");
                return;
            }

            if (txtMaNhanVien1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn mã nhân viên");
                return;
            }

            if (txtMaNCC.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn Mã nhà cung cấp");
                return;
            }

            if (txtNgayNhap1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng Nhập ngày nhập");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int soHang = model.getRowCount();

            if (soHang == 0) {
                JOptionPane.showMessageDialog(null, "Vui lòng thêm hàng.");
                return;
            }
            PhieuNhapModel pn = new PhieuNhapModel();
            pn.setMaPN(txtMaPhieuNhap.getText());
//            pn.setMaNV(txtMaNhanVien1.getText());
            pn.setMaNV(jcbMaNhanVienNhap.getSelectedItem().toString());
            pn.setNgayLap(dateFormat.parse(txtNgayNhap1.getText()));
            pn.setTongGiaTri(Double.parseDouble(txtTong1.getText()));
//            pn.setMaNCC(txtMaNCC.getText());
            pn.setMaNCC(jcbMaNCC.getSelectedItem().toString());
            PhieuNhapControl ctr = new PhieuNhapControl();
            int k = ctr.themPhieuNhap(pn);

            if (k > 0) {
                JOptionPane.showMessageDialog(null, "Lưu phiếu nhập thành công");
                updateSoLuongHangSauKhiNhapHang();
            } else {
                JOptionPane.showMessageDialog(null, "Lưu thất bại");
            }
        } catch (Exception e) {
        }

    }

    private void luuPhieuXuat() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            if (txtMaPhieuXuat.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập Mã phiếu xuất");
                return;
            }

            if (txtMaNhanVien2.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn mã nhân viên");
                return;
            }

            if (txtNgayNhap2.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng Nhập ngày xuất");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            int soHang = model.getRowCount();

            if (soHang == 0) {
                JOptionPane.showMessageDialog(null, "Vui lòng thêm hàng.");
                return;
            }
            PhieuXuatModel px = new PhieuXuatModel();
            px.setMaPhieuXuat(txtMaPhieuXuat.getText());
//            px.setMaNhanVien(txtMaNhanVien2.getText());
            px.setMaNhanVien(jcbMaNhanVienXuat.getSelectedItem().toString());
            px.setNgayXuat(dateFormat.parse(txtNgayNhap2.getText()));
            px.setTongGiaTri(Double.parseDouble(txtTong2.getText()));

            PhieuXuatControl ctr = new PhieuXuatControl();
            int k = ctr.themPhieuXuat(px);

            if (k > 0) {
                JOptionPane.showMessageDialog(null, "Lưu phiếu xuất thành công");
                updateSoLuongHangSauKhiXuatHang();
            } else {
                JOptionPane.showMessageDialog(null, "Lưu thất bại");
            }
        } catch (Exception e) {
        }

    }

//    public void updateSoLuongHangSauKhiNhapHang(String maHang , int soLuong) {
//        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//        int soHang = model.getRowCount();
//        HangModel hang = new HangModel();
//        HangControl hangControl = new HangControl();
//        ArrayList<HangModel> ds = hangControl.layThongTinHang(jcbMaHang1.getSelectedItem().toString());
//        for (HangModel d : ds) {
//            int soLuongMoi = d.getSoLuong() + Integer.parseInt(txtSoLuong1.getText());
//            int k = hangControl.suaSoLuongHangSauKhiNhapHang(jcbMaHang1.getSelectedItem().toString(), soLuongMoi);
//        }
//    }
    public void updateSoLuongHangSauKhiNhapHang() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {

//            System.out.println(model.getValueAt(i, 0));
            HangControl hangControl = new HangControl();
            ArrayList<HangModel> ds = hangControl.layThongTinHang(model.getValueAt(i, 0).toString());

            for (HangModel d : ds) {
                int soLuongMoi = d.getSoLuong() + Integer.parseInt(model.getValueAt(i, 4).toString());
                int k = hangControl.suaSoLuongHangSauKhiNhapHang(model.getValueAt(i, 0).toString(), soLuongMoi);
//            System.out.println(soLuongMoi);
//            System.out.println(k);
            }
        }

    }

    public void updateSoLuongHangSauKhiXuatHang() {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {

//            System.out.println(model.getValueAt(i, 0));
            HangControl hangControl = new HangControl();
            ArrayList<HangModel> ds = hangControl.layThongTinHang(model.getValueAt(i, 0).toString());

            for (HangModel d : ds) {
                int soLuongMoi = d.getSoLuong() - Integer.parseInt(model.getValueAt(i, 4).toString());
                int k = hangControl.suaSoLuongHangSauKhiNhapHang(model.getValueAt(i, 0).toString(), soLuongMoi);
//            System.out.println(soLuongMoi);
//            System.out.println(k);
            }
        }

    }

    //////////////////////Tuan///////////////////
    public void loadComBoBoxMaTang() {
        TangControl TangControl = new TangControl();
        ArrayList<TangModel> ds = TangControl.docThongTinTang();
        DefaultComboBoxModel cbo = new DefaultComboBoxModel();

        for (TangModel d : ds) {
            cbo.addElement(d);
        }
        jcbMaTang.setModel(cbo);
    }

    public void LoadDuLieu3() {
        /////Tabel/////
        HangControl hgcontrol = new HangControl();
        ArrayList<HangModel> ds = hgcontrol.docThongTinHang();
        DefaultTableModel table = new DefaultTableModel();
        table.setRowCount(0);
        table.addColumn("Mã hàng");
        table.addColumn("Tên hàng");
        table.addColumn("Đơn vị tính");
        table.addColumn("Số lượng");
        table.addColumn("Đơn giá");
        table.addColumn("Mã tầng");
        for (HangModel hgmodel : ds) {
            Object[] row = {
                hgmodel.getMaHang(),
                hgmodel.getTenHang(),
                hgmodel.getDonViTinh(),
                hgmodel.getSoLuong(),
                hgmodel.getDonGia(),
                hgmodel.getMaTang(),};
            table.addRow(row);
        }
        tblHang3.setModel(table);
        /////ComboBox/////    
        TangControl tgcontrol = new TangControl();
        ArrayList<TangModel> arr = tgcontrol.docThongTinTang();
        DefaultComboBoxModel cb = new DefaultComboBoxModel();
        for (TangModel tgmodel : arr) {
            cb.addElement(tgmodel);
        }
        cbx3.setModel(cb);
    }

    public void LoadTable3(String matang) {
        HangControl hgcontrol = new HangControl();
        ArrayList<HangModel> ds = hgcontrol.timThongTinHang2(matang);
        DefaultTableModel table = new DefaultTableModel();
        table.setRowCount(0);
        table.addColumn("Mã hàng");
        table.addColumn("Tên hàng");
        table.addColumn("Đơn vị tính");
        table.addColumn("Số lượng");
        table.addColumn("Đơn giá");
        table.addColumn("Mã tầng");
        for (HangModel hgmodel : ds) {
            Object[] row = {
                hgmodel.getMaHang(),
                hgmodel.getTenHang(),
                hgmodel.getDonViTinh(),
                hgmodel.getSoLuong(),
                hgmodel.getDonGia(),
                hgmodel.getMaTang(),};
            table.addRow(row);
        }
        tblHang3.setModel(table);
    }

    public void TimKiem3() {
        HangControl hgcontrol = new HangControl();
        ArrayList<HangModel> ds = hgcontrol.timThongTinHang(txtMaHang3.getText());
        HangModel hgmodel = ds.get(0);
        txtTenHang3.setText(hgmodel.getTenHang());
        txtDonViTinh3.setText(hgmodel.getDonViTinh());
        txtDonGia3.setText(Double.toString(hgmodel.getDonGia()));
        txtSoLuong3.setText(Integer.toString(hgmodel.getSoLuong()));
        txtMaTang3.setText(hgmodel.getMaTang());

        DefaultTableModel table = new DefaultTableModel();
        table.setRowCount(0);
        table.addColumn("Mã hàng");
        table.addColumn("Tên hàng");
        table.addColumn("Đơn vị tính");
        table.addColumn("Số lượng");
        table.addColumn("Đơn giá");
        table.addColumn("Mã tầng");
        Object[] row = {
            hgmodel.getMaHang(),
            hgmodel.getTenHang(),
            hgmodel.getDonViTinh(),
            hgmodel.getSoLuong(),
            hgmodel.getDonGia(),
            hgmodel.getMaTang(),};
        table.addRow(row);
        tblHang3.setModel(table);
    }

    public void LamMoi3() {
        txtMaHang3.setText("");
        txtTenHang3.setText("");
        txtDonViTinh3.setText("");
        txtDonGia3.setText("");
        txtSoLuong3.setText("");
        txtMaTang3.setText("");
        LoadDuLieu3();
    }

    public void Sua3() {
        try {
            HangModel hgmodel = new HangModel();

            hgmodel.setMaHang(txtMaHang3.getText());
            hgmodel.setTenHang(txtTenHang3.getText());
            hgmodel.setDonViTinh(txtDonViTinh3.getText());
            hgmodel.setDonGia(Double.parseDouble(txtDonGia3.getText()));
            hgmodel.setSoLuong(Integer.parseInt(txtSoLuong3.getText()));
            hgmodel.setMaTang(txtMaTang3.getText());

            HangControl hgcontrol = new HangControl();
            if (hgcontrol.suaThongTinHang(hgmodel) > 0) {
                JOptionPane.showMessageDialog(null, "Cập nhật thành công!!!");
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật thất bại!!!");
            }
        } catch (Exception e) {
        }
        LoadDuLieu3();
    }

    public void Them3() {

        if (txtMaHang3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã hàng!");
            return;
        }
        if (txtTenHang3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập tên hàng!");
            return;
        }
        if (txtDonGia3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đơn giá hàng!");
            return;
        }
        if (txtMaTang3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn Mã tầng!");
            return;
        }
        if (txtDonViTinh3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đơn vị tính!");
            return;
        }
        if (txtSoLuong3.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập Số lượng!");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblHang3.getModel();
        int dem = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).toString().equals(txtMaHang3.getText())) {
                dem++;
            }
        }
        if (dem > 0) {
            JOptionPane.showMessageDialog(null, "Mã Hàng này đã tồn tại!!");
        } else {

            HangModel hgmodel = new HangModel();
            hgmodel.setMaHang(txtMaHang3.getText());
            hgmodel.setTenHang(txtTenHang3.getText());
            hgmodel.setDonViTinh(txtDonViTinh3.getText());
            hgmodel.setDonGia(Double.parseDouble(txtDonGia3.getText()));
            hgmodel.setSoLuong(Integer.parseInt(txtSoLuong3.getText()));
            hgmodel.setMaTang(txtMaTang3.getText());

            HangControl hgcontrol = new HangControl();
            if (hgcontrol.themThongTinHang(hgmodel) > 0) {
                JOptionPane.showMessageDialog(null, "Thêm thành công!!!");
                LoadDuLieu3();
                loadComBoBoxMaHang1();
                loadComBoBoxMaHang2();
            } else {
                JOptionPane.showMessageDialog(null, "Thêm thất bại!!!");
            }
        }

    }

    public void Xoa3() {
        String tf = txtMaHang3.getText();
        if (tf.equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã hàng!!!");
            return;
        }

        HangControl hgcontrol = new HangControl();

        int kt = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?");
        if (kt == JOptionPane.YES_OPTION) {
            if (hgcontrol.xoaThongTinHang(txtMaHang3.getText())) {
                JOptionPane.showMessageDialog(null, "Xóa thành công!!!");
                loadComBoBoxMaHang1();
                loadComBoBoxMaHang2();
            } else {
                JOptionPane.showMessageDialog(null, "Xóa thất bại!!!");
            }
        } else {
            return;
        }
        LoadDuLieu3();
    }

    private void tbleHangMouseClickedTUAN(MouseEvent evt) {
        if (this.tblHang3.getSelectedRow() >= 0) {
            String MaHang = this.tblHang3.getValueAt(this.tblHang3.getSelectedRow(), 0).toString();
            txtMaHang3.setText(MaHang);
            String TenHang = this.tblHang3.getValueAt(this.tblHang3.getSelectedRow(), 1).toString();
            txtTenHang3.setText(TenHang);
            String DonGia = this.tblHang3.getValueAt(this.tblHang3.getSelectedRow(), 2).toString();
            txtDonGia3.setText(DonGia);
            String Tang = this.tblHang3.getValueAt(this.tblHang3.getSelectedRow(), 3).toString();
            txtMaTang3.setText(Tang);
            String DonViTinh = this.tblHang3.getValueAt(this.tblHang3.getSelectedRow(), 4).toString();
            txtDonViTinh3.setText(DonViTinh);
            String SoLuong = this.tblHang3.getValueAt(this.tblHang3.getSelectedRow(), 5).toString();
            txtSoLuong3.setText(SoLuong);
        }
    }
}
