/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pc.view;

import java.awt.EventQueue;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pc.controler.HangControl;
import pc.controler.HoaDonControl;
import pc.controler.KhachHangControl;
import pc.controler.NhanVienControl;
import pc.controler.PhieuNhapControl;
import pc.model.HangModel;
import pc.model.HoaDonModel;
import pc.model.KhachHangModel;
import pc.model.NhanVienModel;
import pc.model.PhieuNhapModel;

/**
 *
 * @author Administrator
 */
public class frm_BanHang extends javax.swing.JFrame {

    private double thanhTien = 0;

    /**
     * Creates new form frm_HoaDon
     */
    public frm_BanHang() {
        initComponents();

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Xử lý khi form được đóng
                frm_MeNu formMeNu = new frm_MeNu();
                formMeNu.setVisible(true);
                formMeNu.setLocationRelativeTo(null);
            }
        });
        loadComBoBoxMaHang();
        loadComBoBoxMaNhanVien();
        loadComBoBoxMaKhachHang();
        loadThongTinKhachhang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnThem1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        txtMaHoDon = new javax.swing.JTextField();
        txtMaKhachHang1 = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtNgayLap = new javax.swing.JTextField();
        txtMaNhanVien = new javax.swing.JTextField();
        jcbMaHang = new javax.swing.JComboBox<>();
        jcbMaKhachHang1 = new javax.swing.JComboBox<>();
        jcbMaNhanVien = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtThanhTien = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaKhachHang2 = new javax.swing.JTextField();
        txtTenKhachHang2 = new javax.swing.JTextField();
        txtSoDienThoai2 = new javax.swing.JTextField();
        btnThem2 = new javax.swing.JButton();
        btnXoa2 = new javax.swing.JButton();
        btnSua2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable2 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtDiaChi2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý bán hàng");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mã hóa đơn");

        jLabel2.setText("Mã khách hàng");

        jLabel3.setText("Mã hàng");

        jLabel4.setText("Ngày lập ");

        jLabel5.setText("Mã nhân viên");

        jLabel6.setText("Số lượng");

        btnThem1.setText("Thêm");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnXoa1.setText("Xóa");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        txtMaKhachHang1.setEditable(false);

        txtMaNhanVien.setEditable(false);

        jcbMaKhachHang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMaKhachHang1ActionPerformed(evt);
            }
        });

        jcbMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMaNhanVienActionPerformed(evt);
            }
        });

        jtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hàng", "Tên hàng", "Đơn giá", "Đơn vị tính", "Số lượng"
            }
        ));
        jScrollPane1.setViewportView(jtable1);

        jLabel7.setText("Thành tiền");

        txtThanhTien.setEditable(false);

        jButton3.setText("Lưu và xuất hóa đơn");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Làm mới");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaHoDon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(232, 232, 232))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnXoa1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jcbMaKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(jcbMaHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(btnThem1))))
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(txtNgayLap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaHoDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtMaKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbMaKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem1))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa1))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Hóa đơn", jPanel1);

        jLabel8.setText("Mã khách hàng");

        jLabel9.setText("Tên khách hàng");

        jLabel10.setText("Số điện thoại ");

        btnThem2.setText("Thêm");
        btnThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem2ActionPerformed(evt);
            }
        });

        btnXoa2.setText("Xóa");
        btnXoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa2ActionPerformed(evt);
            }
        });

        btnSua2.setText("Sửa");
        btnSua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua2ActionPerformed(evt);
            }
        });

        jtable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Số điện thoại", "Địa chỉ"
            }
        ));
        jtable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtable2);

        jLabel11.setText("Địa chỉ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaKhachHang2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenKhachHang2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDiaChi2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(41, 41, 41)
                        .addComponent(txtSoDienThoai2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(btnThem2)
                .addGap(36, 36, 36)
                .addComponent(btnSua2)
                .addGap(36, 36, 36)
                .addComponent(btnXoa2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMaKhachHang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtSoDienThoai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenKhachHang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(txtDiaChi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem2)
                    .addComponent(btnSua2)
                    .addComponent(btnXoa2))
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Khách hàng", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 731, 562));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        // TODO add your handling code here:
        xoaThongTinNhapHang();
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void jcbMaKhachHang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMaKhachHang1ActionPerformed
        // TODO add your handling code here:
        txtMaKhachHang1.setText(jcbMaKhachHang1.getSelectedItem().toString());
    }//GEN-LAST:event_jcbMaKhachHang1ActionPerformed

    private void jcbMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMaNhanVienActionPerformed
        // TODO add your handling code here:
        txtMaNhanVien.setText(jcbMaNhanVien.getSelectedItem().toString());
    }//GEN-LAST:event_jcbMaNhanVienActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // TODO add your handling code here:
        loadThongTinNhapHang();
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        luuHoaDon();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem2ActionPerformed
        // TODO add your handling code here:
        themKhachHang();
    }//GEN-LAST:event_btnThem2ActionPerformed

    private void jtable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtable2MouseClicked
        // TODO add your handling code here:
        tbleBanMouseClicked(evt);
    }//GEN-LAST:event_jtable2MouseClicked

    private void btnSua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua2ActionPerformed
        // TODO add your handling code here:
        suaKhachHang();
    }//GEN-LAST:event_btnSua2ActionPerformed

    private void btnXoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa2ActionPerformed
        // TODO add your handling code here:
        xoaKhachHang();
    }//GEN-LAST:event_btnXoa2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        lammoiHoaDon();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_BanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_BanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua2;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnThem2;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JButton btnXoa2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcbMaHang;
    private javax.swing.JComboBox<String> jcbMaKhachHang1;
    private javax.swing.JComboBox<String> jcbMaNhanVien;
    private javax.swing.JTable jtable1;
    private javax.swing.JTable jtable2;
    private javax.swing.JTextField txtDiaChi2;
    private javax.swing.JTextField txtMaHoDon;
    private javax.swing.JTextField txtMaKhachHang1;
    private javax.swing.JTextField txtMaKhachHang2;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtNgayLap;
    private javax.swing.JTextField txtSoDienThoai2;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenKhachHang2;
    private javax.swing.JTextField txtThanhTien;
    // End of variables declaration//GEN-END:variables

    private void tbleBanMouseClicked(MouseEvent evt) {
        if (this.jtable2.getSelectedRow() >= 0) {
            String MaKhachHang = this.jtable2.getValueAt(this.jtable2.getSelectedRow(), 0).toString();
            txtMaKhachHang2.setText(MaKhachHang);
            String TenKhachHang = this.jtable2.getValueAt(this.jtable2.getSelectedRow(), 1).toString();
            txtTenKhachHang2.setText(TenKhachHang);
            String SoDienThoai = this.jtable2.getValueAt(this.jtable2.getSelectedRow(), 2).toString();
            txtSoDienThoai2.setText(SoDienThoai);
            String DiaChi = this.jtable2.getValueAt(this.jtable2.getSelectedRow(), 3).toString();
            txtDiaChi2.setText(DiaChi);
        }
    }

    public void loadComBoBoxMaHang() {
        HangControl hangControl = new HangControl();
        ArrayList<HangModel> ds = hangControl.layThongTinComBoBoxHang();
        DefaultComboBoxModel cbo = new DefaultComboBoxModel();
        for (HangModel d : ds) {
            cbo.addElement(d);
        }
        jcbMaHang.setModel(cbo);
        //jcbMaHang2.setModel(cbo);
    }

    public void loadComBoBoxMaNhanVien() {
        NhanVienControl nvconControl = new NhanVienControl();
        ArrayList<NhanVienModel> ds = nvconControl.layThongTinComBoBoxNhanVien();
        DefaultComboBoxModel cbo = new DefaultComboBoxModel();
        for (NhanVienModel d : ds) {
            cbo.addElement(d);
        }
        jcbMaNhanVien.setModel(cbo);
        //jcbMaNhanVienXuat.setModel(cbo);
    }

    public void loadComBoBoxMaKhachHang() {
        KhachHangControl khachHangControl = new KhachHangControl();
        ArrayList<KhachHangModel> ds = khachHangControl.layThongTinComBoBoxKhachHang();
        DefaultComboBoxModel cbo = new DefaultComboBoxModel();
        for (KhachHangModel d : ds) {
            cbo.addElement(d);
        }
        jcbMaKhachHang1.setModel(cbo);
        //jcbMaNhanVienXuat.setModel(cbo);
    }

    public void loadThongTinNhapHang() {
        String maHang = jcbMaHang.getSelectedItem().toString().substring(0, 4);
        //System.out.println(maHang);
        String soLuong = txtSoLuong.getText();
        int sl;
        double donGia;
        if (soLuong.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số lượng");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();

        HangControl hangControl = new HangControl();
        ArrayList<HangModel> ds = hangControl.layThongTinHang(maHang);

        for (HangModel d : ds) {
            donGia = d.getDonGia();
            sl = Integer.parseInt(soLuong);
            double tongTienHang = donGia * sl;
            thanhTien = thanhTien + tongTienHang;
            Object[] row = {
                d.getMaHang(),
                d.getTenHang(),
                d.getDonGia(),
                d.getDonViTinh(),
                soLuong
            };
            model.addRow(row);
//            int soLuongMoi = d.getSoLuong() + Integer.parseInt(soLuong);
//            int k = hangControl.suaSoLuongHangSauKhiNhapHang(maHang, soLuongMoi);
//            System.out.println(soLuongMoi);
//            System.out.println(k);
        }
        txtThanhTien.setText(String.valueOf(thanhTien));

    }

    public void xoaThongTinNhapHang() {
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        int soHang = model.getRowCount();

        if (soHang == 0) {
            JOptionPane.showMessageDialog(null, "Bảng không có dữ liệu để xóa.");
            return;
        }

        String maHangXoa = jcbMaHang.getSelectedItem().toString();

//        int kiemTraATonTaiMa = -1;
//        for (int i = 0; i < soHang; i++) {
//            if (model.getValueAt(i, 0).equals(maHangXoa)) {
//                kiemTraATonTaiMa = i;
//                break;
//            }
//        }
//        if (kiemTraATonTaiMa != -1) {
//            model.removeRow(kiemTraATonTaiMa);
//        } else {
//            JOptionPane.showMessageDialog(null, "Không tồn tại mã hàng này trong Bảng");
//            return;
//        }
        int selectedRow = jtable1.getSelectedRow();
        if (selectedRow != -1) { // Kiểm tra hàng được chọn có hợp lệ không
            // Xóa hàng khỏi mô hình dữ liệu của JTable
            model.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng để xóa.");
        }

        double tongTien = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            double donGia = (double) model.getValueAt(i, 2);
            int soLuong = Integer.parseInt((String) model.getValueAt(i, 4));
            tongTien += donGia * soLuong;
        }
        thanhTien = tongTien;
        txtThanhTien.setText(String.valueOf(thanhTien));
    }

    public void luuHoaDon() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            if (txtMaHoDon.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập Mã hóa đơn");
                return;
            }

            if (txtMaKhachHang1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng chọn mã Khách hàng");
                return;
            }

            if (txtSoLuong.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng Nhập số lượng");
                return;
            }

            if (txtNgayLap.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng Nhập ngày Lập");
                return;
            }

            if (txtMaNhanVien.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng Chọn mã nhân viên");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
            int soHang = model.getRowCount();

            if (soHang == 0) {
                JOptionPane.showMessageDialog(null, "Vui lòng thêm hàng.");
                return;
            }
            HoaDonModel hd = new HoaDonModel();
            hd.setMaHoaDon(txtMaHoDon.getText());
            hd.setMaNhanVien(txtMaNhanVien.getText());
            hd.setMaKhacHang(txtMaKhachHang1.getText());
            hd.setNgayThang(dateFormat.parse(txtNgayLap.getText()));
            hd.setThanhTien(Double.parseDouble(txtThanhTien.getText()));
            HoaDonControl hdconControl = new HoaDonControl();
            int k = hdconControl.themHoaDon(hd);

            if (k > 0) {
                JOptionPane.showMessageDialog(null, "Lưu hóa đơn thành công");
                updateSoLuongHangSauKhiBan();
                XuatHoaDon();
            } else {
                JOptionPane.showMessageDialog(null, "Lưu thất bại");
            }
        } catch (Exception e) {
        }

    }

    public void updateSoLuongHangSauKhiBan() {
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {

//            System.out.println(model.getValueAt(i, 0));
            HangControl hangControl = new HangControl();
            ArrayList<HangModel> ds = hangControl.layThongTinHang(model.getValueAt(i, 0).toString());

            for (HangModel d : ds) {
                int soLuongMoi = d.getSoLuong() - Integer.parseInt(model.getValueAt(i, 4).toString());
                int k = hangControl.suaSoLuongHangSauKhiNhapHang(model.getValueAt(i, 0).toString(), soLuongMoi);
//            System.out.println(soLuongMoi);
//            System.out.println(k);
            }
        }

    }

    public void loadThongTinKhachhang() {
        KhachHangControl khcontrol = new KhachHangControl();
        ArrayList<KhachHangModel> ds = khcontrol.layThongTinComBoBoxKhachHang();
        DefaultTableModel model = (DefaultTableModel) jtable2.getModel();
        model.setRowCount(0);
        for (int i = 0; i < ds.size(); i++) {
            String makh = ds.get(i).getMaKhachHang();
            String tenkh = ds.get(i).getTenKhachHang();
            String SDT = ds.get(i).getSoDienThoai();
            String diachi = ds.get(i).getDiaChi();
            Object[] row = new Object[]{makh, tenkh, SDT, diachi};
            model.addRow(row);
            jtable2.setModel(model);
        }
    }

    public void themKhachHang() {
        if (txtMaKhachHang2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã Khách Hàng!");
            return;
        }
        if (txtSoDienThoai2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số điện thoại!");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jtable2.getModel();
        int dem = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).toString().equals(txtMaKhachHang2.getText())) {
                dem++;
            }
        }
        if (dem > 0) {
            JOptionPane.showMessageDialog(null, "Mã Khách Hàng này đã tồn tại!!");
        } else {
            KhachHangModel kh = new KhachHangModel();

            kh.setMaKhachHang(txtMaKhachHang2.getText());
            kh.setTenKhachHang(txtTenKhachHang2.getText());
            kh.setSoDienThoai(txtSoDienThoai2.getText());
            kh.setDiaChi(txtDiaChi2.getText());

            KhachHangControl khachHangControl = new KhachHangControl();

            int k = khachHangControl.insertKhachHang(kh);

            if (k > 0) {
                JOptionPane.showMessageDialog(null, " thêm thành công");
                loadThongTinKhachhang();
                loadComBoBoxMaKhachHang();
                lamMoi();
            } else {
                JOptionPane.showMessageDialog(null, " thêm thất bại");
            }

        }
//        else {
//            KhachHangModel kh = new KhachHangModel();
//
//            kh.setMaKhachHang(txtMaKhachHang2.getText());
//            kh.setTenKhachHang(txtTenKhachHang2.getText());
//            kh.setSoDienThoai(txtSoDienThoai2.getText());
//            kh.setDiaChi(txtDiaChi2.getText());
//
//            KhachHangControl khachHangControl = new KhachHangControl();
//
//            int k = khachHangControl.insertKhachHang(kh);
//
//            if (k > 0) {
//                JOptionPane.showMessageDialog(null, " thêm thành công");
//                loadThongTinKhachhang();
//            } else {
//                JOptionPane.showMessageDialog(null, " thêm thất bại");
//            }
//        }

    }

    public void suaKhachHang() {

        if (txtMaKhachHang2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã Khách Hàng!");
        } else {
            DefaultTableModel model = (DefaultTableModel) jtable2.getModel();
            int dem = 0;
            for (int i = 0; i < model.getRowCount(); i++) {
                if (model.getValueAt(i, 0).toString().equals(txtMaKhachHang2.getText())) {
                    dem++;
                }
            }
            if (dem == 0) {
                JOptionPane.showMessageDialog(null, "Không tồn tại mã khách hàng này!!");
            } else {
                KhachHangModel kh = new KhachHangModel();

                kh.setMaKhachHang(txtMaKhachHang2.getText());
                kh.setTenKhachHang(txtTenKhachHang2.getText());
                kh.setSoDienThoai(txtSoDienThoai2.getText());
                kh.setDiaChi(txtDiaChi2.getText());

                KhachHangControl khachHangControl = new KhachHangControl();

                int k = khachHangControl.updateKhachhang(kh);

                if (k > 0) {
                    JOptionPane.showMessageDialog(null, " Cập nhật thành công");
                    loadThongTinKhachhang();
                    lamMoi();
                } else {
                    JOptionPane.showMessageDialog(null, " Cập nhật thất bại");
                }
            }
        }

    }

    public void xoaKhachHang() {
        String tf = txtMaKhachHang2.getText();
        if (tf.equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập mã khách hàng!!!");
            return;
        }

        KhachHangControl khconControl = new KhachHangControl();

        int kt = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?");
        if (kt == JOptionPane.YES_OPTION) {
            if (khconControl.deleteKhachHang(txtMaKhachHang2.getText())) {
                JOptionPane.showMessageDialog(null, "Xóa thành công!!!");
                loadThongTinKhachhang();
                loadComBoBoxMaKhachHang();
                lamMoi();
            } else {
                JOptionPane.showMessageDialog(null, "Xóa thất bại!!!");
            }
        } else {
            return;
        }

    }

    public void lamMoi() {
        txtMaKhachHang2.setText("");
        txtTenKhachHang2.setText("");
        txtSoDienThoai2.setText("");
        txtDiaChi2.setText("");
    }

    private void XuatHoaDon() {
        // Lấy dữ liệu từ tableHoaDon
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        int rowCount = model.getRowCount();

        Object[][] data = new Object[rowCount][3];
        for (int i = 0; i < rowCount; i++) {
            data[i][0] = model.getValueAt(i, 1); // Tên Hàng
            data[i][1] = model.getValueAt(i, 2); // Đơn Giá
            data[i][2] = model.getValueAt(i, 4); // Số Lượng
        }
        String[] columnNames = {"Tên Hàng", "Đơn Giá", "Số Lượng"};

        // Mở form frm_XuatHoaDonBanHang
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                frm_XuatHoaDon frame = new frm_XuatHoaDon();
                frame.setVisible(true);
                frame.updateTable(data);
            }
        });
    }
   public void lammoiHoaDon() {
       txtMaHoDon.setText("");
       txtMaKhachHang1.setText("");
       txtSoLuong.setText("");
       txtNgayLap.setText("");
       txtMaNhanVien.setText("");
       txtThanhTien.setText("");
   }
}
